server:
  port: 8001

spring:
  servlet:
    multipart:
      max-file-size: 1024000MB   #文件上传大小控制
      max-request-size: 1024000MB
  application:
    name: th-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://39.98.86.240:3306/admincloude?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      url: jdbc:mysql://localhost:3306/admincloude?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall,log4j,config
      # 连接池配置
      max-active: 100
      min-idle: 1
      initial-size: 1
      # 连接等待超时时间
      max-wait: 60000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.th.thservice.service.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
          # 添加过滤规则
        url-pattern: /*
          # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

        # 配置StatFilter
      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.th.thservice.entity
#  配置查询语句输出到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

